# Site settings
title: "82L Portfolio"
description: "Doing games, serious games and other things.<br/> Studying at the CNAM ENJMIN to be an engineer in computer science and multimedia"
url: 'https://82l.github.io'
baseurl: ''
bkimage: '/images/bk1.jpg'
font_awesome: 'ead88c3c69.js'
collections:
  projects:
    id: projects
    title: "Game projects"
    icon: "fa-solid fa-gamepad"
    filterProjects:
      - Professional:
        typedesc: "Show professional projects"
        id: 1
      - Student:
        typedesc: "Show student projects"
        id: 2
    keyVal: 1
    output: true
    sort_by: keyVal
  work_projects:
    id: work
    title: "Other IT projects"
    icon: "fa-solid fa-code"
    keyVal: 2
    output: true
    sort_by: keyVal
  misc_projects:
    id: experiments
    title: "Experiments"
    icon: "fa-solid fa-wand-magic-sparkles"
    keyVal: 3
    output: true
    sort_by: keyVal

# you can add collections entries to have different display categories, to better organise the website. 
# be sure to name the folder containing the categories like that _<nameOfCategory>

author:
  name: '82L'
  email: '&#99;o%&#54;E&#116;%&#54;&#49;%6&#51;t&#37;65r82&#108;&#37;4&#48;%&#54;7&#109;a&#105;%6&#67;&#46;co&#109;'
  twitter_username: EightyTwoL
  #  facebook_username:
  github_username:  82l
  gitlab_username:  82l
  itch_username:  82l
  bluesky_username: 82l.bsky.social


socials:
  - link: "https://www.github.com/82l"
    icon: "fab fa-github fa-xl"
    link-title: "See my code on GitHub (main git account)"
  - link: "https://www.gitlab.com/82l"
    icon: "fa-brands fa-gitlab fa-xl"
    link-title: "See my code on GitLab (sub git account)"
  - link: "https://82l.itch.io"
    icon: "fab fa-itch-io fa-xl"
    link-title: "Find my games on Itch"
  - link: "https://bsky.app/profile/82l.bsky.social"
    icon: "fa-brands fa-bluesky fa-xl"
    link-title: "Find me on BlueSky"
  - link: "https://twitter.com/EightyTwoL"
    icon: "fab fa-twitter fa-xl"
    link-title: "Find me on twitter (prefer BlueSky)"
  - link: "ma&#105;lt&#111;&#58;c&#37;6Fnt%61c&#116;er82%6C&#37;40gm%61il&#46;c%6&#70;&#109;"
    icon: "fa-solid fa-envelope fa-xl"
    link-title: "Contact me by mail"

techs:
  csharp:
    label: "C#"
    logo: "/logos/csharp.svg"
  cpp:
    label: "C++"
    logo: "/logos/cpp.svg"
  blender:
    label: "Blender"
    logo: "/logos/blender.svg"
  substance:
    label: "Substance"
    logo: "/logos/substance.svg"
  wood:
    label: "Wood"
  bamboo:
    label: "Bamboo"
  arduino:
    label: "Arduino"
    logo: "/logos/arduino.svg"
  threedprint:
    label: "3d Print"
  photoshop:
    label: "Photoshop"
    logo: "/logos/photoshop.svg"
  illustrator:
    label: "Illustrator"
    logo: "/logos/illustrator.svg"
  electronics:
    label: "Electronics"
  metal:
    label: "Metal"
  capacitor:
    label: "Capacitor"
    logo: "/logos/capacitor.svg"
  jquery:
    label: "JQuery"
    logo: "/logos/jquery.svg"
  node:
    label: "Node.JS"
    logo: "/logos/nodejs.svg"
  php:
    label: "PHP"
    logo: "/logos/php.svg"
  cordova:
    label: "Cordova"
    logo: "/logos/cordova.svg"
  threejs:
    label: "ThreeJS"
    logo: "/logos/threejs.svg"
  unity:
    label: "Unity"
    logo: "/logos/unity.svg"
  scorm:
    label: "Scorm"
  animate:
    label: "Animate"
    logo: "/logos/animate.svg"
  phaser:
    label: "Phaser"
    logo: "/logos/phaser.png"
  twine:
    label: "Twine"
    logo: "/logos/twine.svg"
  webgl:
    label: "WebGL"
    logo: "/logos/webgl.svg"



# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _css
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md']
