# Site settings
title: "82L Portfolio"
description: "Doing games, serious games and other things.<br/> Studying at the CNAM ENJMIN to be an Engineer in computing and multimedia"
url: 'https://82l.github.io'
baseurl: ''
profilepic: '/images/profile.png'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'ead88c3c69.js'
collections:
  work_projects:
    output: true
    sort_by: keyVal
  projects:
    output: true
    sort_by: keyVal
  misc_projects:
    output: true
    sort_by: keyVal
#    label: work_projects



author:
  name: '82L'
  email: contacter82l@gmail.com
#  twitter_username:
#  facebook_username:
  github_username:  82l
  gitlab_username:  82l
  itchio_username:  82l
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV
#email_form: "https://docs.google.com/forms/d/e/1FAIpQLScMSpmmv4D43Xb78ooInG0cjRd5D1UqQsPOlAbQrypOmXA9FA/viewform?embedded=true"
gotProjects: true
#gotResume: true
gotWork: true
gotMisc: true
projectTypes:
  - WoodWorking:
    typedesc : "Show WoodWorking Projects"
    id: 2
  - Forge:
    typedesc : "Show Forge Projects"
    id: 3
  - Other:
    typedesc : "Show Other Projects"
    id: 5

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png', "jekyll-uno-master.zip","jekyll-uno-timeline-master.zip","iframe-resizer-master.zip"]
