# Site settings
title: "82L's Portfolio"
description: "Studying Serious Games while being in apprencticeship."
url: 'https://82l.github.io'
baseurl: ''
profilepic: '/images/profile.png'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'ead88c3c69.js'
collections:
  work_projects:
    output: true
  projects:
    output: true
    sort_by: keyVal
#    label: work_projects



author:
  name: '82L'
 # email: info@thomas-zuehlke.de
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  82l
  itchio_username:  82l
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV
email_form: "https://docs.google.com/forms/d/e/1FAIpQLScMSpmmv4D43Xb78ooInG0cjRd5D1UqQsPOlAbQrypOmXA9FA/viewform?embedded=true"
gotProjects: true
gotResume: true
gotWork: true

projectTypes:
  - VideoGame: 
    typedesc: "Show Video Game Projects"
    id: 1
  - Infography:
    typedesc: "Show Infography Projects"
    id: 4
  - WoodWorking:
    typedesc : "Show WoodWorking Projects"
    id: 2
  - Forge:
    typedesc : "Show Forge Projects"
    id: 3

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png', "jekyll-uno-master.zip","jekyll-uno-timeline-master.zip","iframe-resizer-master.zip"]
